### ISSUE TITLE
IMC_Denoise on M1 Mac

### ISSUE THREAD

**Issue by petesfew** [PENGLU-WashU/IMC_Denoise#8]
Hi,

I am interested in using the DIMR and DeepSNiF algorithms to pre-process my IMC data. However, I have a M1 MacBook and can only use CPU locally to process the data and will not have access to an NVIDIA gpu. In this case, will I still be able to use the DIMR algorithm, and if there is an option to run DeepSNiF on a local gpu or cpu?

**Comment by PENGLU-WashU** [comment]
> Hi,
> 
> I am interested in using the DIMR and DeepSNiF algorithms to pre-process my IMC data. However, I have a M1 MacBook and can only use CPU locally to process the data and will not have access to an NVIDIA gpu. In this case, will I still be able to use the DIMR algorithm, and if there is an option to run DeepSNiF on a local gpu or cpu?

Hi,

Thanks for your interest to our software package. Currently, DeepSNiF can be trained on a cpu, but it could be super slow. At least for now, I encourage you to test our DeepSNiF training using public resources if you cannot get access to an NVIDIA gpu, such as AWS or google colab, We would like to further develop our software on google colab platform and reduce the network size so that training process will be faster. So please keep an eye on our GitHub page.

Best regards.

**Comment by petesfew** [comment]
Hi @PENGLU-WashU 

Thanks for the reply. Will try out the solutions as suggested and look forward to the updates!

**Comment by marivinc** [comment]
Hi,
@petesfew  did the above solutions work for you, or did you ultimately manage to run on the M1 MacBook? Would love to hear which solution worked best for you, as I am in a similar situation now. 
Thanks!
